### ISSUE TITLE
Planting a tree breaks some nodes

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#150]
1) put a jungle sapling or a sapling on some dirt
2) let the tree grow
3) the bottom of the tree is 2 blocks under the sapling vertical position for "saplings", and 4 for jungle saplings. It means that 2 / 4 blocks are wiped.

--> may be a security issue, this might break "unbreakable" blocks.
--> a decent tree-factory would need tons of dirt (at least 1 block per tree), and we have no way to craft it from renewable resources.

proposal:
- change the growing scheme for trees, they MUST not grow under the floor.

- add an easy way (but not that cheap) to craft some dirt. Maybe 2 sands (group) with 2 leaves (group).

Nota Bene: this may affect more sapling than "sapling" and "jungle sapling", we need investigation.
"beech tree sapling" is not affected.

**Comment by gravgun** [comment]
AFAIR (as **few** as I remember) trees didn't grow consuming dirt before the server reset, might be a bug or something...

**Comment by mgl512** [comment]
All the watershed trees like default, jungle, default big pine. The functions are in watershed/functions.lua, named "watershed_<treename>()"

Each tree functions has a code block starting with a line like "for j = -2, 4 do" or "for j = -4, 14 do" or "for j = -5, top". They must be replaced by "for j = 0, 4 do", "for j = 0, 14 do" etc (everything starts at 0) to remove the "tree roots" which are created under the position of the sapling, removing the existing blocks.

In Lord of the Test, this is a feature, not a bug. I don't know for MFF, therefore I won't fix this myself.

**Comment by Ombridride** [comment]
It's not a feature for us, it's a bug, we don't want "roots", we will fix it soon :)

**Comment by mgl512** [comment]
Check that the tree functions I quoted are used for the growing ABM and the mapgen then, because I didn't. They could be redundant elsewhere in watershed.

**Comment by ObaniGemini** [comment]
Mmmh... I think it should be 0, 5    or    0, random(4,5), as trees are very small actually (and also because we would lose 1/3 of trees capacity)

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/25d748c2443b8841d2c974d3cb01cb3a30a17f70
That's the best I can do with my knowledge of map generation in Minetest.

**Comment by mgl512** [comment]
It's ok for me. 

The functions you updated are the mapgen functions. But watershed also redefines the various "default.grow_<treename>" functions that are used by the sapling ABM of minetest_game. They are redefined to use the functions you updated, except for the cactus, which didn't grow underground when you planted one in the game. The case of the cactus is special : there are two pieces of code to grow one. One for the mapgen (in watershed), that you fixed, the other one for the growing ABM (in minetest_game), which didn't have to be fixed. I didn't check that the cactus grows a pair of arms when you plant one. it may not, because the code for its growing ABM doesn't come from watershed but from minetest_game.

**Comment by Ombridride** [comment]
Indeed, we can also change the code of the growing cactus to be like the mapgen cactus

**Comment by mgl512** [comment]
default tree, big snow pine and jungle tree tested and approved in singleplayer with Mg's 25d748c commit. Both as mapgen and as planted saplings. 

As Obani said, it's true that the design of the default tree makes it look small. It looks like a big bush rather than a tree. It still has 6 tree nodes though, instead of 8 when it had roots.

**Comment by Ombridride** [comment]
Ok, thank you for your tests.
Now, maybe we need to add 1or 2 nodes to the default tree trunk to be more high ? (and give again the deleted tree trunks for an easier way to bush wood for players)

**Comment by mgl512** [comment]
Done in commit 96cc41f512. The default tree is randomly 1 or 2 nodes higher with the same design.

**Comment by Ombridride** [comment]
Wow, really good :)

I closed this issue because all of bugs signaled by @Cyberpangolin are now fixed.

**Comment by Cyberpangolin** [comment]
I re-open: the tree now breaks the nodes around it, to replace its schematic by wood. Even very-costly blocks, like node breakers :/

This concerns the wood, probably every type, but not the leaves.

It came with the change to 0.4.13 and the new plants version.

**Comment by LeMagnesium** [comment]
It's not the same bug, but apparently, with the new system using schematics, minetest does not check whether or not it's replacing nodes.

**Comment by Ombridride** [comment]
More information here : https://github.com/minetest/minetest_game/issues/652#issuecomment-135891450

**Comment by paramat** [comment]
See https://github.com/minetest/minetest_game/pull/659

**Comment by paramat** [comment]
Fix merged 73113f344340ca75b5a77961d0d2a205566b1fe4

**Comment by Ombridride** [comment]
Great, thank you @paramat, now we need to merge it on our servers
