### ISSUE TITLE
The area owner mask partialy the HUD

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#194]
I think that the zone of the "area owner name" needs another system of display or wathover because in the spawn it masks completely the HUD

![screenshot_20150807_173100](https://cloud.githubusercontent.com/assets/11613522/9139510/ee7ca29e-3d2a-11e5-8d93-1706cf34a4df.png)

**Comment by Ombridride** [comment]
Sadly, we know this issue since a long time...

I will report it to the area modder, thank you.

**Comment by LeMagnesium** [comment]
I don't think anyone can really do anything except truncate the strings displayed in Area's HUD. That should be easy to do. Yet, knowing that there is no way using Minetest's API to know a player's screen size, and that the HUDs are displayed differently on different screen (because of their size), I don't think we can find a value that everyone would be happy with. For example, for your window's size, we should truncate the strings at about 35 characters, whereas on a fullscreen window on my computer, these lines have enough room to be fully printed. Either we truncate and it might not work everytime and even create problems for others, or we leave it as it is, and just use less long area names.

**Comment by Cyberpangolin** [comment]
Maybe remove the text, add a small hud icon with a locker closed if you are in a restricted area, a locker opened if the area is opened, and the same with a key inside if you are the owner., and the area's number (to manage it)

When you try to break a node in a closed area,  you should have a message, like the news message, telling you "Hey, stop it! You are in the area "$name of area", owned by "$owner".

Of course, if the area is shared between many people, we need something too. Just say this post is my contribution for this brainstorning.
If interested, sure I can make these icons.

**Comment by farfadet46** [comment]
Love it :)

**Comment by Cyberpangolin** [comment]
![cadenasmultiples](https://cloud.githubusercontent.com/assets/12512762/9353266/566d9788-4667-11e5-8067-c9fd615e2bd0.png)
padlock opened: the area is owned by someone but opened to build.
padlock closed: the area is closed (seems trivial...)
if the key is inside, you are the owner of the area (or one of them)

Colour sheme: 
orange for "everyone is free to build, under restrictions (to the owner's discretion) (1 and 2)"
green for "you are free to build, this land is yours (3)"
red for "building here is forbidden"
Maybe I should add something for shared areas (where there are multiple owners), like an orange closed padlock withe the key inside.

these padlocks come from openclipart.

**Comment by farfadet46** [comment]
i think we just need open and closed. in 3 colours of course. i dont realy understand why the key is necessary.
in fact i think if there is no icon, it's free to build :) (no area)

**Comment by LeMagnesium** [comment]
@Cyberpangolin : I like this idea.

**Comment by Cyberpangolin** [comment]
@farfadet46 I think it's very important to know if you are the owner or not, but it's important to know if you have the right to build too and, much more, if your area is opened. When it's opened, maybe someone can improve your building, but he can make undesired changes. That's why we need to say that the area is "owned but opened.", so we make sure the owner always knows about his area's status. An example: palige's public factory in MFF1, where I built tons of things when it was opened, and then he closed it again to make sure nobody griefs.

When you are in free land, without any area, of course there should not be anything.

Oh, and maybe we could add an area button on the main menu:  the owner could 
- click on a lockpad to open / close his own area when he is inside. maybe with a confirmation message, to make sure it's not an accident.
- get the informations he needs about the current area, owners, aso.
- list all his areas?
- get the property born menu to manage his area??

Last (but not least), we could make the red padlock become twice bigger for 0.5 second if you are not allowed to build and you try. A simple but efficient animation that would explain everything :)

With all my apologies to our fantastic coders. :+1:

**Comment by Ombridride** [comment]
Ok for the icon, but how do you know the owners name of the area/subareas with this solution ?

**Comment by Cyberpangolin** [comment]
I'd say in the "main menu" (i keyboard button), a button under the inventory, where you could get the informations (and later get area managing as said in my previous post?)

**Comment by LeMagnesium** [comment]
You still have marker's books to get these informations, or otherwhise, show a truncated version of the full string.

**Comment by Ombridride** [comment]
Refer here https://github.com/ShadowNinja/areas/issues/14 if you ant to follow the feature progression

**Comment by Cyberpangolin** [comment]
Probably someone here should make it if we want to see this feature once.
Any volunteer?

**Comment by crabman77** [comment]
A tester https://github.com/MinetestForFun/server-minetestforfun/commit/6c84995ae01c5d281b133195cad87c9702429948

cadenas vert, c'est a nous, cadenas rouge, ce n'est pas à nous
carre vert, on peut interagir, rouge non
l'outil seulement, c'est openfarming
carre orange c'est à nous mais les autres peuvent interagir (area ouverte) 

![area_info](https://cloud.githubusercontent.com/assets/7189389/13600414/f6118d3e-e528-11e5-80c6-4e0f2a79c666.png)

**Comment by Ombridride** [comment]
Thank you @crabman77 
too many icons types in my point of view, but we will try :)

**Comment by Cyberpangolin** [comment]
up?

**Comment by Ombridride** [comment]
On manque de tests et d'avis

Il faudrait aussi trouver quelque chose de peut-être plus simple car 8 icônes différent ça fait beaucoup, peut être enlevé la notion de "owner" dans les icônes, après tout le pseudo de l'owner est affiché a côté du cadenas donc le joueur peut reconnaitre comme un grand si c'est son pseudo ou pas et par conséquent 
ou je sais pas, peut etre revoir les cadenas, le top serait d'en avoir que 3 ou 4 maximum

**Comment by Cyberpangolin** [comment]
Personellement, je pense que l'on peut tester en l'état sur classic et observer les retours des gens.

Attention: ligne 38, j'ai vu 
+			icon = ("areas_%u_%u_%u.png"):format(mod_owner, mod_open, **mod_arming)**
ne serais-ce pas "mod_farming" plutôt?

**Comment by crabman77** [comment]
"mod_arming" c'était une typo quand j'ai normalisé le nom des variables avec "remplacer tous par" dans l'éditeur, c'est corrigé depuis https://github.com/MinetestForFun/server-minetestforfun/commit/af4a3f47dfcb3e37ee07780a8b17a01ee857220f

Pour les cadenas je veut bien en enlever mais il faut se mettre d'accord avant.

**Comment by Ombridride** [comment]
La simplification que je propose me parait bien, ça serait bien d'avoir des avis dessus

**Comment by ObaniGemini** [comment]
Ou sont les sources des icones de cadenas ? On pourrait envisager de nouveaux icones ?

**Comment by Ombridride** [comment]
Tu peux proposer des icones, pas de soucis :)
Si tu remonte le thread ta les sources de cyber

**Comment by Ombridride** [comment]
The texture will be made by Vault-Boy for this issue. (This is his first issue to become part of our team)

Well, we need 4 textures of "chain" :
- A texture which can say "nothing/free", because the player is in a non-owned area, it's a free area, the player can do what he wants into this area (build, destroy, dig, create areas, etc)
- A green chain texture => The player is into one of its area, owned by him (or one of his friend who give him the privilege on this area) he can do what he wants on this area (build, destroy, dig, create areas, etc)
- An orange chain texture => The player in into an "openfarming area", this kind of area a special, players not-owner of this area can only dig plants/vegetables and put plants/vegetables seeds in this area
- A red chain texture => The actual area you stand into is owned by an another player

Do not hesitate to ask us questions if you needs more details.
You can help you with this textures https://github.com/MinetestForFun/server-minetestforfun/issues/194#issuecomment-193738642 but the needs is something more simple and easy to understand for players

**Comment by ObaniGemini** [comment]
Let's do this

**Comment by Vault-Boy-111** [comment]
ok I completed it the red X is scrappy only because of how the software I used behaves but I think the rest will work http://xomf.com/g/cjygp http://i.xomf.com/kwcpy.png or http://xomf.com/kwcpy click one of them to see them I hope they will work

**Comment by Ombridride** [comment]
@Vault-Boy-111 
To complicated in my point of view, and the small "home" icon can't be  readable ingame, too small

@ObaniGemini 
Sent me this icons beginning, it's simple and can be easily understandable : https://up1.ca/#CdizNpAeatjBkcfWoNNY1A
Maybe color the middle "locks" and/or draw something inside them ? Also they needs to be 64x64

**Comment by ObaniGemini** [comment]
@Ombridride : the idea is to keep it empty for eventual adds : peace area, opened to farming, mining, etc...
If it's empty sometimes and sometimes not it's more noticeable.
I'll make a 64x64 version

**Comment by Cyberpangolin** [comment]
@crabman77 can you put it in the current state ingame? As @ElementW said, it becomes more and more floody with time, particularly on the spawn island...

Thanks :)

**Comment by Cyberpangolin** [comment]
Really better ingame! Thanks a lot!
I close the issue for now, mayber the locker could be tweaked (reduced in size a bit). but it's really really better :+1:
