### ISSUE TITLE
[worldedge] bug

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#241]
Need to check the code of this mod because of a random teleportaiton of UltimateNoob on the server...

_UltimateNoob : and the teleportation bug: main error setting the x cord to infinite so i get teleported in that case_

**Comment by LeMagnesium** [comment]
Apparently what happened is a combination of both a rare server bug I've already heard about, and wolrdedge responding to it. It happens very rarely that one or more coordinates gets increased to an insane level, like x=+2.500e23. It often crashes servers. But when it doesn't, and because minetest can (as far as I remember) accept coordinates out of bouds with a limit of +1000, it may cause worldedge to react and teleport the player.

That should be good enough : https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/65e736b5b1c02636d564f0edaf4b5423fe13d7ae

**Comment by LeMagnesium** [comment]
We've not heard any other problem about corrupted coordinates. I will close this. If somebody gets teleported again, please refer to this issue.
