### ISSUE TITLE
Duplication of items with graveyard

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#325]
from gcrabman : 
```
dans le graveyard, si on click puis on vire en mettant en dehors de l'inventaire sa dedouble
```

**Comment by LeMagnesium** [comment]
I can't reproduce that. What item was thrown away?

**Comment by Ombridride** [comment]
that was the **spears**, but i think you need to speak with @crabman77

**Comment by LeMagnesium** [comment]
It only happens with spears due to the fact that they're throw on drop.
This patch will allow anyone to drop anything from the graveyard at any moment and thus prevent spears from being multiplied when dropped.

https://github.com/MinetestForFun/server-minetestforfun/commit/576d732088733da1e6fd8ed496e9c76e8c5cc7c0
