### ISSUE TITLE
3d_armor|hudbars bug

### ISSUE THREAD

**Issue by crabman77** [MinetestForFun/server-minetestforfun#327]
Même souci(hudbars) que cette issue mais pour 3d_armor https://github.com/MinetestForFun/server-minetestforfun/issues/158

Mettre plusieurs pièces d'armures(identiques), les doublons ne sont pas comptés et la hudbars est correcte, mais si on subit des dégâts:
1) Les doublons sont comptés et le pourcentage peut dépasser 100%
2) La hudbars est déformée + affichage de log en permanence.

![capture](https://cloud.githubusercontent.com/assets/7189389/11445688/a0cab0f2-952e-11e5-8b2f-2c5e77f20d16.jpg)

- [X] fixer 3d_armor : Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/4e89838761e40c80d7e1ba6b66eb0d4f1e2fb996
- [X] fixer hudbars : Fixed https://github.com/MinetestForFun/server-minetestforfun/commit/22efd5dfb766ac7ff2c33e00f434257cbdcea851

**Comment by Ombridride** [comment]
3d_armor => @stujones11
hudbars => @Wuzzy2

**Comment by Wuzzy2** [comment]
@Ombridride: This commit is kinda cheating, it just changes the hudbars mod so it does not show any warnings anymore if you provide out-of-bounds value, which is an important indicator for a possible problem with your mods. I won't merge this into my hudbars mod since it would hide this important warning. This warning was build into hudbars intentionally to warn the user about out-of-bounds mistakes.

It is the responsibility of the user of the hudbars mod to supply values within bounds. If you provide out-of-range values then things go wrong. The fact that the values were wrong means that the armor mod somehow provided values over 100%.

**Comment by Ombridride** [comment]
This thread isn't here to force you with our problems/features, it's just about informing you :)

**Comment by LeMagnesium** [comment]
I don't even get the point of that commit on hudbars, how is it supposed to fix the bug when it comes from 3d_armor?
