### ISSUE TITLE
Creepers blow up NPCs and the landscape.

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/server-minetestforfun#338]
I witnessed a fight between a creeper and a NPC. The creeper exploded, killed both of them and destroyed the landscape. I had to go back home to fetch enough blocks to build back the land. 

When creepers exclusively attacked the players, it was useless to make the destroyed blocks drop as items because there was nobody left to rebuild the landscape. But now that they blow themselves on NPCs, the player is alive and could put the blocks back in place if they were dropped.

**Comment by ObaniGemini** [comment]
So creepers should just ignore NPCs ? Or should they have a second-hand attack especially for non-player ennemies ?

**Comment by mgl512** [comment]
Creepers ignore the NPCs. But the NPCs don't ignore creepers. When a NPC attacks a creeper, it fights back with an explosion. I don't know what we want but I know what we don't want : unaccountable number of explosion holes in the landscape around the player due to constantly spawning creatures fighting each other.

**Comment by Ombridride** [comment]
So, the problem is, the creeper ignore NPCs but when NPCs attack Creepers, the creepers explode ?
This is curious...

In fact the creepers are configured to search and explode only on players, and not to search NPCs (or dogs)

The best solution in my point of view if I understand well the problem is : creepers need to explode on NPCs/dogs BUT with a special explosion which don't destroy lands ?
^ But this solution isn't easy to tweak

**Comment by ObaniGemini** [comment]
I think the problem is more like if monsters always responded to attacks, as for neutral monsters (cows for example).

I think your idea is good @Ombridride.
Maybe that you could use the part of code that protects areas from monsters destructions ?

**Comment by Ombridride** [comment]
@crabman77 can you come here and give us your opinion ? 

I think my solution is too complicated to code, anyway it will include heavy mobs API modifications...

We can surely find something better :)

**Comment by LeMagnesium** [comment]
I personnaly see no bug in the way you describe NPCs and Creepers' interactions. That's how mobs is supposed to work. Although, if it's not already the case, we should make NPCs not attack a monster if it hasn't attacked it yet.

**Comment by ObaniGemini** [comment]
@LeMagnesium : actually the problem is just that creepers will automaticaly destroy terrain if NPCs are generated near them. If you want to apply your idea, maybe only do this for creeper ? ^^

**Comment by Ombridride** [comment]
NPC and Creepers will always attack each other if they are too close, because the mod is made like this

**Comment by LeMagnesium** [comment]
> NPC and Creepers will always attack each other if they are too close, because the mod is made like this

@Ombridride pointed out the most problematic thing about this issue : that's how the mod is supposed to work. So, we can either change the behavior's code (which will be risky) so that neither NPCs nor Creepers attack each other, or make Creepers only able to damage entities (which we do not want), or we keep the code as it is now and just think of a Creeper blast as bad luck.

**Comment by Ombridride** [comment]
It's not a bug, it's a feature.

Anyway, thank you for the report, I closed the issue.
