### ISSUE TITLE
new pig drop 'raw Meat' instead of 'raw porkchop'

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#362]

**Comment by Ombridride** [comment]
Can you explain more your issue please ? 

The "raw porkchop" is a normal feature.
We will not add the "raw meat" instead of "raw porkchop" if it's the purpose of this issue...
The "raw porkchop" give you more life point/satiation

If you have a better name for the "raw porkchop" drop for the new "pig" mob, we are open to your ideas, but this drop won't be erased :)

**Comment by farfadet46** [comment]
actually iwhen i kill a (new) pig I get a beef meat instead of pork meat

**Comment by Ombridride** [comment]
yes, it seems good, ned to check ingame

**Comment by farfadet46** [comment]
ok for now :)
