### ISSUE TITLE
Shared chest : need default Tree leaves.

### ISSUE THREAD

**Issue by fabienwang** [MinetestForFun/server-minetestforfun#368]
Well let's say it's realistic to put a leaf over a steel ingot to get a locked chest or shared locked chest… Ok come on it's a game it's not made to be realistic.

But then, why couldn't we use ANY kind of leaf (maybe even bush leaves) ?

It would really be more coherent to accept the "group" leaves, and we could maybe do the same about the steel ingot and allow any of the group as well.

Thanks in advance for your feedbacks about it

**Comment by Ombridride** [comment]
Great feedback, we will make more coherent the craft recipe of locked chests with your proposals

**Comment by fabienwang** [comment]
I could help, Let me make a pull request about it tonight ? :)

**Comment by Ombridride** [comment]
Of course you can, it will be very helpful for us ! :)
Currently it's a little difficult in our side, many bugs to fix(Classic) and many improves to code (Skyblock) =)

**Comment by LeMagnesium** [comment]
Ok.
Why? Why should we modify the recipe? What's the arguement?

**Comment by fabienwang** [comment]
@LeMagnesium I'd just allow any kind of leaves to be used in that recipe (which means the group)
not change the steel ingot thing. I think it would be more coherent

**Comment by LeMagnesium** [comment]
Ok, I looked at the recipe. I was confused when you talked about Default's locked chests, but since shared chests already have a leaves block in their recipes I'm ok with switching to `group:leaves`.
So there you have it, it doesn't take much time to do : https://github.com/MinetestForFun/server-minetestforfun/commit/88ee617741c4a488e7fdf03dd67493787c1f0f83

**Comment by fabienwang** [comment]
Thanks :heart_eyes:
