### ISSUE TITLE
a "monster" for dungeon master?

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#372]
I was killed by a dungeon master. not a "monster"...
![capture du 2016-01-07 20 19 00](https://cloud.githubusercontent.com/assets/12512762/12180421/b794f57c-b57c-11e5-88f8-4f2fc4a5f7dc.png)

**Comment by Ombridride** [comment]
Curious bug https://github.com/MinetestForFun/server-minetestforfun/blob/72232087a618cbf947d9535ae7abc90d8926ecb9/mods/death_messages/init.lua#L119

I think it's because of the new attack type of the Dungeon Master, they can now attack directly with they arms players,  so if a players is dead without fireball and with a direct hit of a DM, the message shouldn't be good.

@LeMagnesium it's your baby, can you fix it please ? (if you can teak your code to works well with the Yeti, if im right, he can hit players like DM if there are close to it with his arms)
