### ISSUE TITLE
Add this mod ? [central_message]

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#384]
https://forum.minetest.net/viewtopic.php?f=9&t=12720

I think this mod would be very useful for warning messages, they would be seen easily by players (for example errors at the entry-quizz).
Any other ideas ? (event timer for example :smile:  )

**Comment by Ombridride** [comment]
I already see it, we don't need this mod on Classic/Creative server, on HG/SB a similar mod is already installed

**Comment by LeMagnesium** [comment]
I find this display method quite annoying, but that's only my personal opinion. On Cr and Cl, @Ombridride said, we don't need them, indeed. Hg has the hudkit-based HUD to warn players whenever they need to do something important. Sb doesn't really have a similar mechanism, but it is not important there.
If anybody has anything to say, please do so, otherwise, I think we won't let that issue rot here long.

**Comment by ObaniGemini** [comment]
Well this could be useful on the server for reboots, or informations at first entry to the server (e.g : "You didn't answer correctly the quizz"). Many players don't see the chat at first so this mod could be useful mostly for those players.

**Comment by LeMagnesium** [comment]
> Well this could be useful on the server for reboots
Yes, I agree, except for when you notify of reboots just before rebooting. Then they won't see the message.

> or informations at first entry to the server (e.g : "You didn't answer correctly the quizz").
Such informations are usually sent in the chat, where the players should be looking for them. I personally find that adding a mod for such purposes only is a bit overkill. Also, **If we had colours** they could help catch the players' attention, but sadly, we do not.

**Comment by Ombridride** [comment]
This feature isn't needed, i closed the issue.
