### ISSUE TITLE
About magical powers

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#388]
Hey I just saw this mod and thought about using it https://forum.minetest.net/viewtopic.php?f=9&t=13965
It's admin toys. It enables the admin to do several things to players, like huge jumps, weird controlling changes,etc...

I think this mod could be used as a start for those magical powers we talked about a long time ago.
Don't you think ?

**Comment by LeMagnesium** [comment]
Well, antigraviity, fast, and confusion could definetly be powers, I even recall that the old potion_modpack had all of them. Glide is also a consequence of gravity modification, so it's feasible and consistent. But the rest is just... trolly... and not very useful to players, even to throw to each other. So those are basic powers we could extract from that mod, but they're not that hard to recode actually...
The mod itself is useless to us, since we had these ideas or because they were already part of previous magic mods.
(and by the way I might get to work on runes, magic and some point of the wizard class during and/or before vacations)

**Comment by Ombridride** [comment]
we already know this mod, and it will be use in the future if we made someday the wizard class :)

Anyway, Tank you for the informations. I closed the issue.
