### ISSUE TITLE
Change nyan items [nyancats_plus]

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#391]
https://forum.minetest.net/viewtopic.php?f=9&t=13961

This mod adds nyancat_shards from nyancat rainbows. I think e should add this mod and maybe replace our actual nyan tools textures with the ones from this mod.
It would make nyan tools more accessible, used, and with a simpler texture.

**Comment by LeMagnesium** [comment]
We could create those shards inside default and change the recipes there.

**Comment by ObaniGemini** [comment]
Yes, but the idea is still from the mode. It's not about implementing the mod in itself, but what it adds to the game

**Comment by Ombridride** [comment]
I Totally disagree with this mod, the *Nyan tools* actual implementation is great, simple, stable, balanced... Well, perfect !

So... Why did you want to add complexity, use code we don't know if it's stable, didn't used the textures we made.

The Nyan shards aren't usefull at all...

**Comment by LeMagnesium** [comment]
If the idea is adding this mod then I can only agree with @Ombridride even though I think nyan shards could become items (although not used to craft nyan tools). Thanks for the proposition.

**Comment by ObaniGemini** [comment]
The idea, for it is clear, is to add the Nyan shards and to recreate the crafts with them (for tools). And maybe to change the textures.

**Comment by Ombridride** [comment]
The shards will be a balance problem for the craft recipe, anyway i don't think it's useful.

The craft recipe with nyan_block works great, If a nyan_block = 9*shards what's the difference ? Just put shards instead of nyan_blocks, if you want shards because of nyan tools easier to craft, or because you think shards are cool, we can't add it just for this positive argument :p

Again, shards will add just a more complex craft system, we don't need it...

**Comment by Ombridride** [comment]
Closed the issue because of my last comment.
