### ISSUE TITLE
river water infinite source

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun#403]
Put 2 water sources on 3 blocks: source - nothing - source
"nothing" becomes a water source

do the same with river water
-> you have an infinite source of tears because it doesn't work

**Comment by LeMagnesium** [comment]
We could make river water a renewable liquid like normal water, although it would probably not be a good idea. River water was specifically coded not to be renewable since it is used to generate rivers, and sometimes, rivers fall down a hill or a small pile of nodes and their configuration would make river water sources multiply themselves and ruin the generated illusion of a river.

**Comment by Ombridride** [comment]
Yes, it's a normal feature and we won't add the infinite river water source for biome reasons

**Comment by Cyberpangolin** [comment]
ok, then I will make a river with standard water.
