### ISSUE TITLE
Move factories to space !

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#408]
The idea is to move factories to a high area ( +2000 ? +3000 ?) and to create warps to reach them.
This would avoid the problem of players creating lags when generating the chunks where they are located.

We would also need to  protect the factories to protect players from falling, but *this is up to the owners/builders of the factory*.

I'm thinking to :
- @Cyberpangolin 's factories
- @farfadet46 's factories
- others ?

I know this is not a really cool solution and any other ideas are welcome, but those are really lag machines (litterally). This is a problem especially for big factories, we don't need that for little ones, I think.

**Comment by farfadet46** [comment]
my factory are not always open, and i open it only when i'm the only player on the server.
the best lag is only when player generate chunk (like mining or explorring i think)
maybe nether is laggy too :)

**Comment by ObaniGemini** [comment]
@farfadet46 : do you mean that it is not always set on ?

**Comment by farfadet46** [comment]
sorry, yes it's very rarely set on and if i set on, it's when i'm alone on the server.
my factory is just some testing and for Understanding in mesecon ;)

**Comment by Cyberpangolin** [comment]
@ObaniGemini I'm a bit confused: if people are generating chunks, it's a generation problem.
https://github.com/MinetestForFun/server-minetestforfun/issues/380 refers to that, it will be done soon.

If you mean that the factories are too laggy, I think the best way is to improve mesecons and not move them away. Mesecons IS a lag machine in itself, even if there were some improvements during the last year.

 I've not had any complaint for month about the public factory, that was optimized again and again. there is even an automatic stop for the stone generation, when the chests are full (ie: never, because everyone uses it.).
 About the woodcutter's house, I can surely improve it and add an on/off button, but after testing, 2 players (Uraza and me) near it generate 1.2s of lag. When I'm alone the max lag decreases to 0.8s, it's not a big value if you consider the informations need to cross the Atlantic ocean twice. A strange thing with it: when unloaded and re-loaded, all trees are popped, and there is a rush for 5 seconds of leaves decaying and vacuumed. it's the only moment you should have real lags there.

My other factories are under my house. If you go inside, you may lag but you are perfectly safe.
@Ombridride Probably @paly2 's moremesecons could improve the situation, with adjustable blinky plants to slow the things down.

@farfadet46 to try mesecons tricks, feel free to use the chlorine server (I can give you the adress if you need it). It's there for a testing purpose and you can have creative in the classic game to make sure it's as near a possible of the classic game :).

So, ATM, I think we have tons of other thing to do before resign to move the factories away.

**Comment by ObaniGemini** [comment]
I think the problem is mainly when they are turned on, which rarely happends. There wasn't tons of player sin the same area but we supposed it could be one of the reasons of the lag, as no one was generating. I keep this issue for the moment if someone thinks it cold be a good idea. Mesecons is a lag machine when it is set on ;)

**Comment by Ombridride** [comment]
In my point of view, what's @ObaniGemini point out, isn't necessary for now.

**Comment by Cyberpangolin** [comment]
I close it for now, there is nothing new about it.
Probably #412 doesn't help for lag.
