### ISSUE TITLE
Bow damages PVE / PVP

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun#419]
I found this bug :
- When you throw an arrow on a mob, the damage calculation is correct, the "bow type" damage is added with the arrow damage and the monster take this damage sum
- When you throw an arrow on a player, the damage calculation is not correct, the "bow type" damage isn't added with the arrow damage and the player takes ONLY the arrow damage

**Comment by LeMagnesium** [comment]
What arrows did you use?

**Comment by Ombridride** [comment]
i tried with all arrows

**Comment by LeMagnesium** [comment]
All damages (except blast physics ones) are managed with `obj:punch`, I didn't see anything related to bows.

**Comment by Ombridride** [comment]
@crabman77 
Tu pourrais regarder s'il te plait ?

**Comment by LeMagnesium** [comment]
So I checked and I know why all of this doesn't work : armor groups.

Take a cow for example. Its armor groups are `{fleshy=200}`, and a diamond arrow with the royal bow will inflict 18HP of damage. Now, take a dirtmonster, its armor groups are `{fleshy=100}`, and the same weapons will only give 9HP of damage. In a similar fashion, the player will always have half the damage of a cow with the same arrow/bow since its fleshy armor is twice lower (for some reason).
So there is no real way of unifying damages to mobs and players, some animals are just weaker.

**Comment by crabman77** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun/commit/e9d29dc779797839d9d121730b13870129e79856

**Comment by Ombridride** [comment]
Merci pour le fix, je clos le ticket.
