### ISSUE TITLE
Remove some unused parts of mesecons

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun#421]
Everyrthing in the title.
Our subgame is very heavy and it would be good to light it a bit.
Some parts of mesecons mode are unused/unuseful or "duplicated".
Here is a list of what I propose to remove from the modpack :

- ~~blinkyplant~~
- ~~commandblock (main use replaced by warps)~~
- [ ] movestones
- [ ] mvps
- [ ] noteblock ? (a bit useless and contains many datas)
- [ ] powerplant (replaced by torch)
- ~~switch (walllever is doing the same thing)~~
- ~~stickyblocks (buggy and unused)~~

What do you think of it ?

**Comment by farfadet46** [comment]
i think blinkyplant isn't useless :/

**Comment by ObaniGemini** [comment]
I put some "?" where I waswn't sure. Blinky plant isn't useless but can be replaced by some other things.

**Comment by Cyberpangolin** [comment]
:-1: :-1: :-1: 

@ObaniGemini it's not because you don't use something that it needs to be removed.

- blinky plant is an absolute necessary thing, we don't have any other way to make a regular blink that is light in resources. I already tried to find something to replace it, it was terrible in resources consumption.

- command block: what if @Ombridride wants to make a special event?

- movestone: top for hidden ways. I never used it, but I already planned to.

- mvps: What's that?

- noteblock: fun. Not often used, but it can add something to the game.

- powerplant: it has a fundamental difference with the torch: it is not stopped if a mesecons signal is under it.

- switch / lever: not at all the same design. 

- sticky blocks are not bugged: they do exactly what their are programmed for. I discovered their introduction weeks ago withe @paly2 , and REALLY want to try them once.

Yes: the subgame is heavy, but I would prefer to see why it keeps the pipes loaded and remove that instead of castrate mesecons. Of course some of the nodes you talk about are not often used, but it doesn't mean we have to remove them.  I never asked to remove xdecor or factions, even if I ~never used them, and don't intend to (because they are not what I like to do in MT).
Should I?

Furthermore, their weight in kB is insignificant, and while they are not used they won't make you lag.

Last (but not least) it means that any mesecons update would need to be tweaked before being applied into MinetestForFun.

**Comment by LeMagnesium** [comment]
>  movestones
mvps
noteblock ? (a bit useless and contains many datas)
powerplant (replaced by torch)

Powerplants are vital (they're the power sources), and so is mvps (it contains the functions for pistons and movestones).
Three out of those 4 only declare nodes and have little to almost no impact on runtime lag (powerplant, noteblock, mvps kinda). Only one out of those 4 uses audio media files, although they are quite small (noteblock).
To put it in perspective, mobs is twice larger than the whole modpack of mesecons. Although it was possible for mobs, it's not safe nor a good idea to cut out parts of mesecons.

**Comment by Ombridride** [comment]
Thank you for your answers @Cyberpangolin @LeMagnesium 

Like I said  before to @ObaniGemini this issue isn't useful in my point of view.
The problem isn't the mesecons tools BUT the mesecons code/way it's coded... (in a really weird way...)

**Comment by ObaniGemini** [comment]
Ok. But can't powerplant be replaced by mese torch ?
