### ISSUE TITLE
problem with HUD

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#454]
when i get the reward for the daily quest (charbon) i get some visual errors in the HUD
- the bags icons (on bottom right disapear)
- the satiation bar is deleted

![bug minetest](https://cloud.githubusercontent.com/assets/11613522/15331482/bb18cd12-1c61-11e6-84e2-eae9eb1f3c1e.png)

**Comment by LeMagnesium** [comment]
It's for @ElementW , but I guess it's the engine's fault. Any insight?

**Comment by ElementW** [comment]
It's a long-standing issue and I very highly suspect Minetest core's not doing its job properly (eh, what did you expect). Mods register and update UI elements through a numeric ID the creation function returns, but none of the mods we use change their element IDs variables (because it'd make absolutely no sense).

I've had my `quests` fork have issues updating progress bars. It was extremely irritating, I ended up making it delete and recreate all UI elements rather than updating. It wasn't supposed to happen.

Now those pesky mods are messing with elements other than theirs (bags wrongly updating, accidentally removing the satiation bar), which of darn course isn't supposed to happen either, and I can confirm the mods are *not* at fault (have a peek at [`inventory_icon/init.lua`](https://github.com/MinetestForFun/server-minetestforfun/blob/master/mods/inventory_icon/init.lua), it never changes its HUD IDs).

**Comment by Darcidride** [comment]
Surely, Minetest Core related... sadly we can't fix it... I closed the issue.

**Comment by crabman77** [comment]
Fixed https://github.com/MinetestForFun/quests/commit/48dd7aa04570f6b10b867d287a15bcfdd99c70a3

**Comment by Darcidride** [comment]
Thank you @crabman77

**Comment by Cyberpangolin** [comment]
Merci @crabman77 !
