### ISSUE TITLE
some items pictures are wrong

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun#455]
![capture](https://cloud.githubusercontent.com/assets/11613522/15448228/301943b0-1f5c-11e6-8069-6fcf2b6db1ce.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11613522/15448229/303eb6cc-1f5c-11e6-81d3-17f6f0fa5e94.PNG)
![capture3](https://cloud.githubusercontent.com/assets/11613522/15448230/30425a34-1f5c-11e6-8b82-beaf5508e687.PNG)

**Comment by crabman77** [comment]
fixed door tin https://github.com/MinetestForFun/server-minetestforfun/commit/48d535a8941ead1c1345b141e5cb5f8ad0aa1e22

**Comment by LeMagnesium** [comment]
I feer that the dyes' problem might be a rendering bug, or some combination or textures not properly rendered...

**Comment by LeMagnesium** [comment]
OK, now this is getting weird..
![](https://lut.im/Ri9zvH8HDr/dPb7ry48VM2mFYow)

Here's a screenshot of a medium lime, lime and magenta stained glass once placed. I tried removing the texture files for the lime stained glass, and the magenta texture kept being applied onto it..
I'm really thinking that this is engine-level of bug..

**Comment by Ombridride** [comment]
Damn, thsi isn't a good news...

**Comment by ElementW** [comment]
Texture corruption has been a thing in Minetest since long ago. IIRC the Irrlicht engine is responsible of some of these issues, the rest is MT being unable to properly handle its resources due to poorly written code.

Unless you get to track down what pieces of code were executed (and with which data) to give these results -- implying using tools like `callgrind` --, nothing of that will get fixed, especially considering the evergoing MT coredev mindset of "doesn't happen to me/happens rarely, `WONTFIX`".
