### ISSUE TITLE
a few  incoherence between blocks

### ISSUE THREAD

**Issue by ezamlinux** [MinetestForFun/server-minetestforfun#487]
- [X] The 'Sandstone Stair' and 'Sandstone Brick Stair' are breakable by hand ( While Sandstone Brick, Sandstone block and cobble/brick stair not)

- [X] The 'Old Red Sandstone Cobble' are diggable by hand ( The name implies that it is hard/solid like a cobblestone ... ) and this "stair craft" give us 8 while others materials 6.

- [x] The 'Junglewood Plank' give 4 'jungle stick' while others plank 9  'stick'. Also, I think there is no specific recipe ... maybe replaced by stick.

- [ ] The 'Tree' (default:tree) is the only trunk to give us 9 plank, other tree give 4.

**Comment by LeMagnesium** [comment]
I don't really agree on the idea of cobble necessarily being a hard material. Cobblestone is only hard because it is made of stone. Old Red Sandstone is supposed to be weak and sandy, so, even compacted into cobble, it is still diggable by hand.
However the recipe for stairs were indeed inconsistent. Fixed.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/64b6a872d0d9c9e5b311eef02044bd6bd5ac359d

**Comment by LeMagnesium** [comment]
(who changed the issue?)
