### ISSUE TITLE
Crash when opening a written book

### ISSUE THREAD

**Issue by sys4-fr** [MinetestForFun/server-minetestforfun#536]
I don't know exactly what is the root cause of this issue and I avoid to reproduce it directly on the server.
In my NALC branch, the issue is avoided because the minetest_game is updated to the backport-0.4 branch.

If I have the time, I will try to isolate the issue and will propose a PR to fix it.

**Comment by LeMagnesium** [comment]
It seems that the current code for books works for versions beyond 0.4.15. We've never upgraded to 0.4.16 and will, in fact, most likely skip that version for 0.5.0.
Now, I'll work on a patch that determines what behavior must be used for what version of the engine so that older and more recent versions can work together with the code we pulled from minetest_game.

**Comment by LeMagnesium** [comment]
This commit is to be blamed, I didn't check compatibility with 0.4.15 : https://github.com/MinetestForFun/server-minetestforfun/commit/27a7195c5292492cd33f24e4451d9d50b7b03d98
It's been fixed and the code was reverted to what it was in 0.4.15 on minetest_game. I'll work on a special branch for all the changes necessary so that minetestforfun's classic code runs on 0.4.16 and beyond.

**Comment by LeMagnesium** [comment]
Also, fixed by essentially doing what you did and revert to the backport's code : https://github.com/MinetestForFun/server-minetestforfun/commit/e0bf0f23247b2b2d337bd1751582efcd260d6406
